name = "hackathon_api"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-02"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hackathon"
database_id = "e05e7327-bd0e-44ad-8789-fff3426440a8"
migrations_dir = "drizzle/migrations"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[triggers]
crons = ["* * * * *"]