name = "hackathon_api"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-02"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
FIREBASE_PROJECT_ID = "dd-daily-calendar"
FIREBASE_SERVICE_ACCOUNT="ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGQtZGFpbHktY2FsZW5kYXIiLAogICJwcml2YXRlX2tleV9pZCI6ICJiNGViYmNkYzU0YzJmZjY3ZmUwMjRlOWQxOWNmMmY5YmJiMmU1ZDE2IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUURTQllVQWlNWlNRRWgyXG40UjdabmM0Sjcxb2JWU1BQbUJmQ281Z1lmQ1Ztb2w3dGFUVWo2ZDUyUUhnNnk5UVdRNTE5UDdXYk4xZk9URUlyXG5YN293UDBsc1VqVkFHc2U2RnFBT2NSUThzUE10VW5zeW4vOHM2RTNna0s4Y1ZmWGxlQk5RUWl6RU5NdC9yRXdIXG51bHAyOEYwV0lhd013ejdjeUJaT1E0ZFY5Wm1xVVJRaVJzdHc4UDJPSmtVdzZGdGt4N2Z0U3VYbFBVWlV4RnFNXG5JTU1BUjVzVzhTdDVUWG9jV01wNzBXczBsTHdkQ2U0eTBYZFFaKy9adkw1Vm9CRUZIVm8rL3JQazh4MzF0d2FmXG55MHBwVU9VZDBCeTdDOUMyeUlDV3FhbFozZHlUWkpXdUFJRHZqUVp6b1RwTU1KajB3THoveWFKeFZxaXFXSnVoXG5LRXJPV2h4VkFnTUJBQUVDZ2dFQUZxZTB4SzE4WXpQKy9SL2tvWW5seDJtVDJUM3lhbnJZR1UxblkwREZFaEN5XG4xNzVSRnFvc0xxcGVyY3o5K0ZiYjNyNW9Hekc1blkzWlYyOXdtTExDKzFYVTI3RG4yWm1HTTNpY083M0V4WjlQXG5uZExuaGxNYXozNGIvWjBDTlBvaWJ6WnNPTkFQSVpzVzZvQitNTFZWL1VTdG1BVFp1NXd6MThadUMyWSthTUk3XG5HMFN5aFhMTVJqbjNJZzg5VEJVZjBFRGVGZXR2RFMxRVMvblBEK0RvRHFXV2ZPcDBwWWhQSFFEemFWZStMRTd3XG5OdkNONkdiZFNZNno4MnF3SUxJVjJIeW9uRk9UQVpYWTFLd2RnTUtibTV5ZnNjbjB0MWc3MTZlSVFYU0FoT0doXG5admVtc1JwdDEwWmoxN0NJWUllbGZ2V1VMMkJ1U0F5K0Z5bkw1SnhJc3dLQmdRRDRKNTRENW90aTh4YTVIeWhnXG5CaVVBZzhkd0QvWWE0dkIzQXUvUVpKc1NKRjdOenZ4TGtjeVdlMWUzOW9sOXEybmtQVzV2dll0TzFRK0lVQVhHXG44S1RyYkFOTEFYNHZybm44MHlNVGFjamtJY1JIaUUrZWFKWTJsNzhpVll6NmJLUG5Nb0YrVHNvK3RUWDh2U0ExXG5nZUNRRS80b3hnYWNrZmlMbUVjRmdOK1R6d0tCZ1FEWXFVZTRtUkc2cHdDQmxjaDZrZ1hzTnFwYmtiQVRuUHNTXG5MNmRKYTFtdk9Mb2ZKVFJJVG5BQnc3N25kNmJHQUZCb2VkdTZ0eXdwVytBTlhxU0pKYTUxcGNEVlhKMTFPL2EzXG53cnlyRDlLV1J6dFpqa3FlSWpObm82WUpMbFNkT2V2ajVETnVKbVdBRy90cDg2V215RkVaOFRTdkIyNTZSVWJ4XG4wYnU4Syt3Q213S0JnUUNSRWxBTlJiVU01c0hNL1lzVC8rT1gxbkk4Y0FoWEZYNndoSllBQlNDbXpYNWk0UE9iXG5saU85Z1dQNWx2WXY4b3JZTkpXZ1czWGFZekpPWlVITFdKbUJTOGJ0RFhWZ21LYVdDRFRFUDU2Q3g3N0FkczdjXG44NVdGV3RjUlVtUTFibGV2YkZaSnFmUVFEczM5Nys2cGVVRDMyY2hHdStYWG1IcHQyVnNEdTZCNC93S0JnQVZlXG5iSUNPaW5udG1YMmNrSk00K3h5WFhqRldzdDVKalk4dHp4OXFvWlpOK1k2OEJVZWxhZkVoUUtITHZUNDYwOE5EXG5BY2Jtc3hselJXSVBibFJYc3JNSG9IZXBDOTNUMXBGSEtoV3pGcXpTcHczWkVOQktXS3ZBeW1SLzJXanIvb1J2XG5LemNYakh4WU5TcXk5dS9qRnQ5bHNzQ0RscUZCQmprSDBYY2dQNER4QW9HQUN1MGVGRlliTjg4cGFQV2M1V0I5XG5NVE83OEZUdGlKZlNpTndqMEIvRXFURFN1czBWeVIxdk43OEM4ZFZZeExTWjZQZWhBWG1icXNuS2doUGFkM0lUXG5MdVpRa3hLdFo2Zk9ScUoyTHE4emxUbnJXM1RDK2pGcXd4VUczbk1YSDdzb0FqN1JmOEhqSEJpWVVoTDZ3b1RUXG5veEN2SXllb29ZSVJFUVlQMm1JbStDbz1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay1nMnhlMkBkZC1kYWlseS1jYWxlbmRhci5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTIwODE4MTA3Nzc5MDU0MDQzMzIiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWcyeGUyJTQwZGQtZGFpbHktY2FsZW5kYXIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hackathon"
database_id = "e05e7327-bd0e-44ad-8789-fff3426440a8"
migrations_dir = "drizzle/migrations"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[triggers]
crons = ["* * * * *"]